# Generated by Django 2.0.4 on 2018-05-01 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('data_saida', models.DateTimeField(null=True, verbose_name='Saída')),
                ('total_horas', models.IntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name_plural': 'Acessos',
                'verbose_name': 'Acesso',
            },
        ),
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cartao_rfid', models.CharField(max_length=100, null=True, verbose_name='Cartão RFID')),
                ('tipo_bolsa', models.IntegerField(choices=[(0, 'Voluntário'), (1, 'Remunerado')], verbose_name='Tipo')),
                ('carga_horaria_semanal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carga Horaria (semanal)')),
            ],
            options={
                'verbose_name_plural': 'Bolsistas',
                'verbose_name': 'Bolsista',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Professores',
                'verbose_name': 'Professor',
            },
        ),
        migrations.AddField(
            model_name='bolsista',
            name='professor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_professor', to='app.Professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='bolsista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_acesso', to='app.Bolsista', verbose_name='Bolsista'),
        ),
    ]
