# Generated by Django 2.0.4 on 2018-05-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Orientador', 'verbose_name_plural': 'Orientadores'},
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='matricula',
            field=models.CharField(max_length=100, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='professor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_professor', to='app.Professor', verbose_name='Orientador'),
        ),
    ]
