# Generated by Django 2.0.4 on 2018-05-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='total_horas',
            field=models.IntegerField(blank=True, verbose_name='Total'),
        ),
    ]
