# Generated by Django 2.0.5 on 2018-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acesso_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
