# Generated by Django 2.0.4 on 2018-05-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180501_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
