# Generated by Django 2.0.4 on 2018-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180501_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data_entrada',
            field=models.DateTimeField(verbose_name='Entrada'),
        ),
    ]
