# Generated by Django 2.0.4 on 2018-06-09 00:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180608_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='matricula',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\d]+$'), 'O nome de usuário só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Matricula'),
        ),
    ]
