# Generated by Django 2.0.4 on 2018-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180501_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acesso',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='acesso',
            name='data_saida',
        ),
        migrations.AddField(
            model_name='acesso',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída'),
        ),
    ]
