# Generated by Django 2.0.4 on 2018-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180501_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='total_horas',
            field=models.DurationField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
