# Generated by Django 2.0.4 on 2018-06-17 17:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180608_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='matricula',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.RegexValidator(re.compile('^[\\d]+$'), 'A matrícula só pode conter números', 'invalid')], verbose_name='Matricula'),
        ),
    ]
