# Generated by Django 2.0.4 on 2018-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180507_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data Acesso'),
        ),
    ]
