# Generated by Django 2.0.4 on 2018-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_acesso_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
