# Generated by Django 2.0.4 on 2018-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180617_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='cartao_rfid',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Cartão RFID'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='tipo_bolsa',
            field=models.IntegerField(choices=[(0, 'VOLUNTÁRIO'), (1, 'REMUNERADO')], verbose_name='Tipo'),
        ),
    ]
