# Generated by Django 2.0.4 on 2018-05-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180507_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='total_horas',
            field=models.DurationField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
