# Generated by Django 2.0.4 on 2018-06-18 15:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180618_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[A-Z][Á-Ú]+$'), 'O nome só pode conter letras', 'invalid')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[A-Z][Á-Ú]+$'), 'O nome só pode conter letras', 'invalid')], verbose_name='Nome'),
        ),
    ]
